### ISSUE TITLE
Windows Negfix8 script Link on README is broken. 

### ISSUE THREAD

**Issue by martinjmartinez** [alibosworth/pakon-planar-raw-converter#24]
[Negfix8 script](https://sites.google.com/site/negfix/downloads)

**Comment by alibosworth** [comment]
Thanks, duplicate of https://github.com/alibosworth/pakon-planar-raw-converter/issues/22

**Comment by alibosworth** [comment]
Thanks Duplicate of https://github.com/alibosworth/pakon-planar-raw-converter/issues/22
